# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.batch.v1beta1.JobTemplateSpec
JobTemplateSpec describes the data a Job should have when created from a template

    IoK8sApiBatchV1beta1JobTemplateSpec(;
        metadata=nothing,
        spec=nothing,
    )

    - metadata::IoK8sApimachineryPkgApisMetaV1ObjectMeta
    - spec::IoK8sApiBatchV1JobSpec
"""
Base.@kwdef mutable struct IoK8sApiBatchV1beta1JobTemplateSpec <: OpenAPI.APIModel
    metadata = nothing # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1ObjectMeta }
    spec = nothing # spec type: Union{ Nothing, IoK8sApiBatchV1JobSpec }

    function IoK8sApiBatchV1beta1JobTemplateSpec(metadata, spec, )
        OpenAPI.validate_property(IoK8sApiBatchV1beta1JobTemplateSpec, Symbol("metadata"), metadata)
        OpenAPI.validate_property(IoK8sApiBatchV1beta1JobTemplateSpec, Symbol("spec"), spec)
        return new(metadata, spec, )
    end
end # type IoK8sApiBatchV1beta1JobTemplateSpec

const _property_types_IoK8sApiBatchV1beta1JobTemplateSpec = Dict{Symbol,String}(Symbol("metadata")=>"IoK8sApimachineryPkgApisMetaV1ObjectMeta", Symbol("spec")=>"IoK8sApiBatchV1JobSpec", )
OpenAPI.property_type(::Type{ IoK8sApiBatchV1beta1JobTemplateSpec }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiBatchV1beta1JobTemplateSpec[name]))}

function check_required(o::IoK8sApiBatchV1beta1JobTemplateSpec)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiBatchV1beta1JobTemplateSpec }, name::Symbol, val)
end
