# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.core.v1.LocalObjectReference
LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.

    IoK8sApiCoreV1LocalObjectReference(;
        name=nothing,
    )

    - name::String : Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
"""
Base.@kwdef mutable struct IoK8sApiCoreV1LocalObjectReference <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing

    function IoK8sApiCoreV1LocalObjectReference(name, )
        OpenAPI.validate_property(IoK8sApiCoreV1LocalObjectReference, Symbol("name"), name)
        return new(name, )
    end
end # type IoK8sApiCoreV1LocalObjectReference

const _property_types_IoK8sApiCoreV1LocalObjectReference = Dict{Symbol,String}(Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ IoK8sApiCoreV1LocalObjectReference }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiCoreV1LocalObjectReference[name]))}

function check_required(o::IoK8sApiCoreV1LocalObjectReference)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiCoreV1LocalObjectReference }, name::Symbol, val)
end
