# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.batch.v2alpha1.CronJobStatus
CronJobStatus represents the current state of a cron job.

    IoK8sApiBatchV2alpha1CronJobStatus(;
        active=nothing,
        lastScheduleTime=nothing,
    )

    - active::Vector{IoK8sApiCoreV1ObjectReference} : A list of pointers to currently running jobs.
    - lastScheduleTime::ZonedDateTime : Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
"""
Base.@kwdef mutable struct IoK8sApiBatchV2alpha1CronJobStatus <: OpenAPI.APIModel
    active::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{IoK8sApiCoreV1ObjectReference} }
    lastScheduleTime::Union{Nothing, ZonedDateTime} = nothing

    function IoK8sApiBatchV2alpha1CronJobStatus(active, lastScheduleTime, )
        OpenAPI.validate_property(IoK8sApiBatchV2alpha1CronJobStatus, Symbol("active"), active)
        OpenAPI.validate_property(IoK8sApiBatchV2alpha1CronJobStatus, Symbol("lastScheduleTime"), lastScheduleTime)
        return new(active, lastScheduleTime, )
    end
end # type IoK8sApiBatchV2alpha1CronJobStatus

const _property_types_IoK8sApiBatchV2alpha1CronJobStatus = Dict{Symbol,String}(Symbol("active")=>"Vector{IoK8sApiCoreV1ObjectReference}", Symbol("lastScheduleTime")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ IoK8sApiBatchV2alpha1CronJobStatus }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiBatchV2alpha1CronJobStatus[name]))}

function check_required(o::IoK8sApiBatchV2alpha1CronJobStatus)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiBatchV2alpha1CronJobStatus }, name::Symbol, val)
    if name === Symbol("lastScheduleTime")
        OpenAPI.validate_param(name, "IoK8sApiBatchV2alpha1CronJobStatus", :format, val, "date-time")
    end
end
