# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.batch.v1.Job
Job represents the configuration of a single job.

    IoK8sApiBatchV1Job(;
        apiVersion=nothing,
        kind=nothing,
        metadata=nothing,
        spec=nothing,
        status=nothing,
    )

    - apiVersion::String : APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    - kind::String : Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    - metadata::IoK8sApimachineryPkgApisMetaV1ObjectMeta
    - spec::IoK8sApiBatchV1JobSpec
    - status::IoK8sApiBatchV1JobStatus
"""
Base.@kwdef mutable struct IoK8sApiBatchV1Job <: OpenAPI.APIModel
    apiVersion::Union{Nothing, String} = nothing
    kind::Union{Nothing, String} = nothing
    metadata = nothing # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1ObjectMeta }
    spec = nothing # spec type: Union{ Nothing, IoK8sApiBatchV1JobSpec }
    status = nothing # spec type: Union{ Nothing, IoK8sApiBatchV1JobStatus }

    function IoK8sApiBatchV1Job(apiVersion, kind, metadata, spec, status, )
        OpenAPI.validate_property(IoK8sApiBatchV1Job, Symbol("apiVersion"), apiVersion)
        OpenAPI.validate_property(IoK8sApiBatchV1Job, Symbol("kind"), kind)
        OpenAPI.validate_property(IoK8sApiBatchV1Job, Symbol("metadata"), metadata)
        OpenAPI.validate_property(IoK8sApiBatchV1Job, Symbol("spec"), spec)
        OpenAPI.validate_property(IoK8sApiBatchV1Job, Symbol("status"), status)
        return new(apiVersion, kind, metadata, spec, status, )
    end
end # type IoK8sApiBatchV1Job

const _property_types_IoK8sApiBatchV1Job = Dict{Symbol,String}(Symbol("apiVersion")=>"String", Symbol("kind")=>"String", Symbol("metadata")=>"IoK8sApimachineryPkgApisMetaV1ObjectMeta", Symbol("spec")=>"IoK8sApiBatchV1JobSpec", Symbol("status")=>"IoK8sApiBatchV1JobStatus", )
OpenAPI.property_type(::Type{ IoK8sApiBatchV1Job }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiBatchV1Job[name]))}

function check_required(o::IoK8sApiBatchV1Job)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiBatchV1Job }, name::Symbol, val)
end
