# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.policy.v1beta1.RunAsGroupStrategyOptions
RunAsGroupStrategyOptions defines the strategy type and any options used to create the strategy.

    IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions(;
        ranges=nothing,
        rule=nothing,
    )

    - ranges::Vector{IoK8sApiPolicyV1beta1IDRange} : ranges are the allowed ranges of gids that may be used. If you would like to force a single gid then supply a single range with the same start and end. Required for MustRunAs.
    - rule::String : rule is the strategy that will dictate the allowable RunAsGroup values that may be set.
"""
Base.@kwdef mutable struct IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions <: OpenAPI.APIModel
    ranges::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{IoK8sApiPolicyV1beta1IDRange} }
    rule::Union{Nothing, String} = nothing

    function IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions(ranges, rule, )
        OpenAPI.validate_property(IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions, Symbol("ranges"), ranges)
        OpenAPI.validate_property(IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions, Symbol("rule"), rule)
        return new(ranges, rule, )
    end
end # type IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions

const _property_types_IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions = Dict{Symbol,String}(Symbol("ranges")=>"Vector{IoK8sApiPolicyV1beta1IDRange}", Symbol("rule")=>"String", )
OpenAPI.property_type(::Type{ IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions[name]))}

function check_required(o::IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions)
    o.rule === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiPolicyV1beta1RunAsGroupStrategyOptions }, name::Symbol, val)
end
