# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.core.v1.PodDNSConfigOption
PodDNSConfigOption defines DNS resolver options of a pod.

    IoK8sApiCoreV1PodDNSConfigOption(;
        name=nothing,
        value=nothing,
    )

    - name::String : Required.
    - value::String
"""
Base.@kwdef mutable struct IoK8sApiCoreV1PodDNSConfigOption <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function IoK8sApiCoreV1PodDNSConfigOption(name, value, )
        OpenAPI.validate_property(IoK8sApiCoreV1PodDNSConfigOption, Symbol("name"), name)
        OpenAPI.validate_property(IoK8sApiCoreV1PodDNSConfigOption, Symbol("value"), value)
        return new(name, value, )
    end
end # type IoK8sApiCoreV1PodDNSConfigOption

const _property_types_IoK8sApiCoreV1PodDNSConfigOption = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ IoK8sApiCoreV1PodDNSConfigOption }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiCoreV1PodDNSConfigOption[name]))}

function check_required(o::IoK8sApiCoreV1PodDNSConfigOption)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiCoreV1PodDNSConfigOption }, name::Symbol, val)
end
