# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.core.v1.PersistentVolumeClaimCondition
PersistentVolumeClaimCondition contails details about state of pvc

    IoK8sApiCoreV1PersistentVolumeClaimCondition(;
        lastProbeTime=nothing,
        lastTransitionTime=nothing,
        message=nothing,
        reason=nothing,
        status=nothing,
        type=nothing,
    )

    - lastProbeTime::ZonedDateTime : Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    - lastTransitionTime::ZonedDateTime : Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    - message::String : Human-readable message indicating details about last transition.
    - reason::String : Unique, this should be a short, machine understandable string that gives the reason for condition&#39;s last transition. If it reports \&quot;ResizeStarted\&quot; that means the underlying persistent volume is being resized.
    - status::String
    - type::String
"""
Base.@kwdef mutable struct IoK8sApiCoreV1PersistentVolumeClaimCondition <: OpenAPI.APIModel
    lastProbeTime::Union{Nothing, ZonedDateTime} = nothing
    lastTransitionTime::Union{Nothing, ZonedDateTime} = nothing
    message::Union{Nothing, String} = nothing
    reason::Union{Nothing, String} = nothing
    status::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing

    function IoK8sApiCoreV1PersistentVolumeClaimCondition(lastProbeTime, lastTransitionTime, message, reason, status, type, )
        OpenAPI.validate_property(IoK8sApiCoreV1PersistentVolumeClaimCondition, Symbol("lastProbeTime"), lastProbeTime)
        OpenAPI.validate_property(IoK8sApiCoreV1PersistentVolumeClaimCondition, Symbol("lastTransitionTime"), lastTransitionTime)
        OpenAPI.validate_property(IoK8sApiCoreV1PersistentVolumeClaimCondition, Symbol("message"), message)
        OpenAPI.validate_property(IoK8sApiCoreV1PersistentVolumeClaimCondition, Symbol("reason"), reason)
        OpenAPI.validate_property(IoK8sApiCoreV1PersistentVolumeClaimCondition, Symbol("status"), status)
        OpenAPI.validate_property(IoK8sApiCoreV1PersistentVolumeClaimCondition, Symbol("type"), type)
        return new(lastProbeTime, lastTransitionTime, message, reason, status, type, )
    end
end # type IoK8sApiCoreV1PersistentVolumeClaimCondition

const _property_types_IoK8sApiCoreV1PersistentVolumeClaimCondition = Dict{Symbol,String}(Symbol("lastProbeTime")=>"ZonedDateTime", Symbol("lastTransitionTime")=>"ZonedDateTime", Symbol("message")=>"String", Symbol("reason")=>"String", Symbol("status")=>"String", Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ IoK8sApiCoreV1PersistentVolumeClaimCondition }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiCoreV1PersistentVolumeClaimCondition[name]))}

function check_required(o::IoK8sApiCoreV1PersistentVolumeClaimCondition)
    o.status === nothing && (return false)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiCoreV1PersistentVolumeClaimCondition }, name::Symbol, val)
    if name === Symbol("lastProbeTime")
        OpenAPI.validate_param(name, "IoK8sApiCoreV1PersistentVolumeClaimCondition", :format, val, "date-time")
    end
    if name === Symbol("lastTransitionTime")
        OpenAPI.validate_param(name, "IoK8sApiCoreV1PersistentVolumeClaimCondition", :format, val, "date-time")
    end
end
