# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.core.v1.ResourceRequirements
ResourceRequirements describes the compute resource requirements.

    IoK8sApiCoreV1ResourceRequirements(;
        limits=nothing,
        requests=nothing,
    )

    - limits::Dict{String, String} : Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
    - requests::Dict{String, String} : Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
"""
Base.@kwdef mutable struct IoK8sApiCoreV1ResourceRequirements <: OpenAPI.APIModel
    limits::Union{Nothing, Dict{String, String}} = nothing
    requests::Union{Nothing, Dict{String, String}} = nothing

    function IoK8sApiCoreV1ResourceRequirements(limits, requests, )
        OpenAPI.validate_property(IoK8sApiCoreV1ResourceRequirements, Symbol("limits"), limits)
        OpenAPI.validate_property(IoK8sApiCoreV1ResourceRequirements, Symbol("requests"), requests)
        return new(limits, requests, )
    end
end # type IoK8sApiCoreV1ResourceRequirements

const _property_types_IoK8sApiCoreV1ResourceRequirements = Dict{Symbol,String}(Symbol("limits")=>"Dict{String, String}", Symbol("requests")=>"Dict{String, String}", )
OpenAPI.property_type(::Type{ IoK8sApiCoreV1ResourceRequirements }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiCoreV1ResourceRequirements[name]))}

function check_required(o::IoK8sApiCoreV1ResourceRequirements)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiCoreV1ResourceRequirements }, name::Symbol, val)
end
