# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.flowcontrol.v1alpha1.UserSubject
UserSubject holds detailed information for user-kind subject.

    IoK8sApiFlowcontrolV1alpha1UserSubject(;
        name=nothing,
    )

    - name::String : &#x60;name&#x60; is the username that matches, or \&quot;*\&quot; to match all usernames. Required.
"""
Base.@kwdef mutable struct IoK8sApiFlowcontrolV1alpha1UserSubject <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing

    function IoK8sApiFlowcontrolV1alpha1UserSubject(name, )
        OpenAPI.validate_property(IoK8sApiFlowcontrolV1alpha1UserSubject, Symbol("name"), name)
        return new(name, )
    end
end # type IoK8sApiFlowcontrolV1alpha1UserSubject

const _property_types_IoK8sApiFlowcontrolV1alpha1UserSubject = Dict{Symbol,String}(Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ IoK8sApiFlowcontrolV1alpha1UserSubject }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiFlowcontrolV1alpha1UserSubject[name]))}

function check_required(o::IoK8sApiFlowcontrolV1alpha1UserSubject)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiFlowcontrolV1alpha1UserSubject }, name::Symbol, val)
end
