# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApiV1StorageOSVolumeSource <: SwaggerModel

    function IoK8sKubernetesPkgApiV1StorageOSVolumeSource(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1StorageOSVolumeSource

const _name_map_IoK8sKubernetesPkgApiV1StorageOSVolumeSource = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApiV1StorageOSVolumeSource = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApiV1StorageOSVolumeSource }) = _name_map_IoK8sKubernetesPkgApiV1StorageOSVolumeSource
Swagger.field_map(::Type{ IoK8sKubernetesPkgApiV1StorageOSVolumeSource }) = _field_map_IoK8sKubernetesPkgApiV1StorageOSVolumeSource

function check_required(o::IoK8sKubernetesPkgApiV1StorageOSVolumeSource)
    true
end

function validate_field(o::IoK8sKubernetesPkgApiV1StorageOSVolumeSource, name::Symbol, val)
end
