# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec <: SwaggerModel

    function IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec

const _property_map_IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec = Dict{Symbol,Symbol}()
const _property_types_IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec = Dict{Symbol,String}()
Base.propertynames(::Type{ IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec }) = collect(keys(_property_map_IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec))
Swagger.property_type(::Type{ IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec[name]))}
Swagger.field_name(::Type{ IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec }, property_name::Symbol) =  _property_map_IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec[property_name]

function check_required(o::IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec)
    true
end

function validate_property(::Type{ IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewSpec }, name::Symbol, val)
end
