# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus <: SwaggerModel
    observedGeneration::Nullable{ Int64 } # observedGeneration
    replicas::Nullable{ Int32 } # replicas

    function IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus(;observedGeneration=nothing, replicas=nothing)
        o = new()
        set_field!(o, :observedGeneration, observedGeneration)
        set_field!(o, :replicas, replicas)
        o
    end
end # type IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus

const _name_map_IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus = Dict{String,Symbol}(["observedGeneration"=>:observedGeneration, "replicas"=>:replicas])
const _field_map_IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus = Dict{Symbol,String}([:observedGeneration=>"observedGeneration", :replicas=>"replicas"])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus }) = _name_map_IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus }) = _field_map_IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus

function check_required(o::IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus)
    isnull(o.replicas) && (return false)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisAppsV1beta1StatefulSetStatus, name::Symbol, val)
end
