# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1beta1NetworkPolicyIngressRule <: SwaggerModel
    from::Nullable{ Vector{V1beta1NetworkPolicyPeer} } # from
    ports::Nullable{ Vector{V1beta1NetworkPolicyPort} } # ports

    function V1beta1NetworkPolicyIngressRule(;from=nothing, ports=nothing)
        o = new()
        set_field!(o, :from, from)
        set_field!(o, :ports, ports)
        o
    end
end # type V1beta1NetworkPolicyIngressRule

const _name_map_V1beta1NetworkPolicyIngressRule = Dict{String,Symbol}(["from"=>:from, "ports"=>:ports])
Swagger.name_map(::Type{ V1beta1NetworkPolicyIngressRule }) = _name_map_V1beta1NetworkPolicyIngressRule

function check_required(o::V1beta1NetworkPolicyIngressRule)
    true
end

function validate_field(o::V1beta1NetworkPolicyIngressRule, name::Symbol, val)
end
