# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sApiSchedulingV1beta1PriorityClass <: SwaggerModel
    apiVersion::Union{ Nothing, String } # apiVersion
    description::Union{ Nothing, String } # description
    globalDefault::Union{ Nothing, Bool } # globalDefault
    kind::Union{ Nothing, String } # kind
    metadata::Union{ Nothing, IoK8sApimachineryPkgApisMetaV1ObjectMeta } # metadata
    value::Union{ Nothing, Int32 } # value

    function IoK8sApiSchedulingV1beta1PriorityClass(;apiVersion=nothing, description=nothing, globalDefault=nothing, kind=nothing, metadata=nothing, value=nothing)
        o = new()
        set_field!(o, :apiVersion, apiVersion)
        set_field!(o, :description, description)
        set_field!(o, :globalDefault, globalDefault)
        set_field!(o, :kind, kind)
        set_field!(o, :metadata, metadata)
        set_field!(o, :value, value)
        o
    end
end # type IoK8sApiSchedulingV1beta1PriorityClass

const _name_map_IoK8sApiSchedulingV1beta1PriorityClass = Dict{String,Symbol}(["apiVersion"=>:apiVersion, "description"=>:description, "globalDefault"=>:globalDefault, "kind"=>:kind, "metadata"=>:metadata, "value"=>:value])
const _field_map_IoK8sApiSchedulingV1beta1PriorityClass = Dict{Symbol,String}([:apiVersion=>"apiVersion", :description=>"description", :globalDefault=>"globalDefault", :kind=>"kind", :metadata=>"metadata", :value=>"value"])
Swagger.name_map(::Type{ IoK8sApiSchedulingV1beta1PriorityClass }) = _name_map_IoK8sApiSchedulingV1beta1PriorityClass
Swagger.field_map(::Type{ IoK8sApiSchedulingV1beta1PriorityClass }) = _field_map_IoK8sApiSchedulingV1beta1PriorityClass

function check_required(o::IoK8sApiSchedulingV1beta1PriorityClass)
    (o.value === nothing) && (return false)
    true
end

function validate_field(o::IoK8sApiSchedulingV1beta1PriorityClass, name::Symbol, val)
end
