# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sApiSettingsV1alpha1PodPreset <: SwaggerModel
    apiVersion::Nullable{ String } # apiVersion
    kind::Nullable{ String } # kind
    metadata::Nullable{ IoK8sApimachineryPkgApisMetaV1ObjectMeta } # metadata
    spec::Nullable{ IoK8sApiSettingsV1alpha1PodPresetSpec } # spec

    function IoK8sApiSettingsV1alpha1PodPreset(;apiVersion=nothing, kind=nothing, metadata=nothing, spec=nothing)
        o = new()
        set_field!(o, :apiVersion, apiVersion)
        set_field!(o, :kind, kind)
        set_field!(o, :metadata, metadata)
        set_field!(o, :spec, spec)
        o
    end
end # type IoK8sApiSettingsV1alpha1PodPreset

const _name_map_IoK8sApiSettingsV1alpha1PodPreset = Dict{String,Symbol}(["apiVersion"=>:apiVersion, "kind"=>:kind, "metadata"=>:metadata, "spec"=>:spec])
const _field_map_IoK8sApiSettingsV1alpha1PodPreset = Dict{Symbol,String}([:apiVersion=>"apiVersion", :kind=>"kind", :metadata=>"metadata", :spec=>"spec"])
Swagger.name_map(::Type{ IoK8sApiSettingsV1alpha1PodPreset }) = _name_map_IoK8sApiSettingsV1alpha1PodPreset
Swagger.field_map(::Type{ IoK8sApiSettingsV1alpha1PodPreset }) = _field_map_IoK8sApiSettingsV1alpha1PodPreset

function check_required(o::IoK8sApiSettingsV1alpha1PodPreset)
    true
end

function validate_field(o::IoK8sApiSettingsV1alpha1PodPreset, name::Symbol, val)
end
