# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset <: SwaggerModel

    function IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset

const _name_map_IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset }) = _name_map_IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset }) = _field_map_IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset

function check_required(o::IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisSettingsV1alpha1PodPreset, name::Symbol, val)
end
