# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback <: SwaggerModel

    function IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback

const _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback }) = _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback }) = _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback

function check_required(o::IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisExtensionsV1beta1DeploymentRollback, name::Symbol, val)
end
