# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sApiCoreV1PodAffinityTerm <: SwaggerModel
    labelSelector::Union{ Nothing, IoK8sApimachineryPkgApisMetaV1LabelSelector } # labelSelector
    namespaces::Union{ Nothing, Vector{String} } # namespaces
    topologyKey::Union{ Nothing, String } # topologyKey

    function IoK8sApiCoreV1PodAffinityTerm(;labelSelector=nothing, namespaces=nothing, topologyKey=nothing)
        o = new()
        set_field!(o, :labelSelector, labelSelector)
        set_field!(o, :namespaces, namespaces)
        set_field!(o, :topologyKey, topologyKey)
        o
    end
end # type IoK8sApiCoreV1PodAffinityTerm

const _name_map_IoK8sApiCoreV1PodAffinityTerm = Dict{String,Symbol}(["labelSelector"=>:labelSelector, "namespaces"=>:namespaces, "topologyKey"=>:topologyKey])
const _field_map_IoK8sApiCoreV1PodAffinityTerm = Dict{Symbol,String}([:labelSelector=>"labelSelector", :namespaces=>"namespaces", :topologyKey=>"topologyKey"])
Swagger.name_map(::Type{ IoK8sApiCoreV1PodAffinityTerm }) = _name_map_IoK8sApiCoreV1PodAffinityTerm
Swagger.field_map(::Type{ IoK8sApiCoreV1PodAffinityTerm }) = _field_map_IoK8sApiCoreV1PodAffinityTerm

function check_required(o::IoK8sApiCoreV1PodAffinityTerm)
    (o.topologyKey === nothing) && (return false)
    true
end

function validate_field(o::IoK8sApiCoreV1PodAffinityTerm, name::Symbol, val)
end
