# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApiV1NamespaceList <: SwaggerModel

    function IoK8sKubernetesPkgApiV1NamespaceList(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1NamespaceList

const _name_map_IoK8sKubernetesPkgApiV1NamespaceList = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApiV1NamespaceList = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApiV1NamespaceList }) = _name_map_IoK8sKubernetesPkgApiV1NamespaceList
Swagger.field_map(::Type{ IoK8sKubernetesPkgApiV1NamespaceList }) = _field_map_IoK8sKubernetesPkgApiV1NamespaceList

function check_required(o::IoK8sKubernetesPkgApiV1NamespaceList)
    true
end

function validate_field(o::IoK8sKubernetesPkgApiV1NamespaceList, name::Symbol, val)
end
