# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""The node this Taint is attached to has the \&quot;effect\&quot; on any pod that does not tolerate the Taint.

    IoK8sApiCoreV1Taint(;
        effect=nothing,
        key=nothing,
        timeAdded=nothing,
        value=nothing,
    )

    - effect::String : Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
    - key::String : Required. The taint key to be applied to a node.
    - timeAdded::IoK8sApimachineryPkgApisMetaV1Time : TimeAdded represents the time at which the taint was added. It is only written for NoExecute taints.
    - value::String : Required. The taint value corresponding to the taint key.
"""
mutable struct IoK8sApiCoreV1Taint <: SwaggerModel
    effect::Any # spec type: Union{ Nothing, String } # spec name: effect
    key::Any # spec type: Union{ Nothing, String } # spec name: key
    timeAdded::Any # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1Time } # spec name: timeAdded
    value::Any # spec type: Union{ Nothing, String } # spec name: value

    function IoK8sApiCoreV1Taint(;effect=nothing, key=nothing, timeAdded=nothing, value=nothing)
        o = new()
        validate_property(IoK8sApiCoreV1Taint, Symbol("effect"), effect)
        setfield!(o, Symbol("effect"), effect)
        validate_property(IoK8sApiCoreV1Taint, Symbol("key"), key)
        setfield!(o, Symbol("key"), key)
        validate_property(IoK8sApiCoreV1Taint, Symbol("timeAdded"), timeAdded)
        setfield!(o, Symbol("timeAdded"), timeAdded)
        validate_property(IoK8sApiCoreV1Taint, Symbol("value"), value)
        setfield!(o, Symbol("value"), value)
        o
    end
end # type IoK8sApiCoreV1Taint

const _property_map_IoK8sApiCoreV1Taint = Dict{Symbol,Symbol}(Symbol("effect")=>Symbol("effect"), Symbol("key")=>Symbol("key"), Symbol("timeAdded")=>Symbol("timeAdded"), Symbol("value")=>Symbol("value"))
const _property_types_IoK8sApiCoreV1Taint = Dict{Symbol,String}(Symbol("effect")=>"String", Symbol("key")=>"String", Symbol("timeAdded")=>"IoK8sApimachineryPkgApisMetaV1Time", Symbol("value")=>"String")
Base.propertynames(::Type{ IoK8sApiCoreV1Taint }) = collect(keys(_property_map_IoK8sApiCoreV1Taint))
Swagger.property_type(::Type{ IoK8sApiCoreV1Taint }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiCoreV1Taint[name]))}
Swagger.field_name(::Type{ IoK8sApiCoreV1Taint }, property_name::Symbol) =  _property_map_IoK8sApiCoreV1Taint[property_name]

function check_required(o::IoK8sApiCoreV1Taint)
    (getproperty(o, Symbol("effect")) === nothing) && (return false)
    (getproperty(o, Symbol("key")) === nothing) && (return false)
    true
end

function validate_property(::Type{ IoK8sApiCoreV1Taint }, name::Symbol, val)
end
