# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy <: SwaggerModel

    function IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy

const _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy }) = _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy }) = _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy

function check_required(o::IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisExtensionsV1beta1DaemonSetUpdateStrategy, name::Symbol, val)
end
