# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApiV1Taint <: SwaggerModel

    function IoK8sKubernetesPkgApiV1Taint(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1Taint

const _name_map_IoK8sKubernetesPkgApiV1Taint = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApiV1Taint = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApiV1Taint }) = _name_map_IoK8sKubernetesPkgApiV1Taint
Swagger.field_map(::Type{ IoK8sKubernetesPkgApiV1Taint }) = _field_map_IoK8sKubernetesPkgApiV1Taint

function check_required(o::IoK8sKubernetesPkgApiV1Taint)
    true
end

function validate_field(o::IoK8sKubernetesPkgApiV1Taint, name::Symbol, val)
end
