# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApiV1ServicePort <: SwaggerModel

    function IoK8sKubernetesPkgApiV1ServicePort(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1ServicePort

const _name_map_IoK8sKubernetesPkgApiV1ServicePort = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApiV1ServicePort = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApiV1ServicePort }) = _name_map_IoK8sKubernetesPkgApiV1ServicePort
Swagger.field_map(::Type{ IoK8sKubernetesPkgApiV1ServicePort }) = _field_map_IoK8sKubernetesPkgApiV1ServicePort

function check_required(o::IoK8sKubernetesPkgApiV1ServicePort)
    true
end

function validate_field(o::IoK8sKubernetesPkgApiV1ServicePort, name::Symbol, val)
end
