# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sApiCoreV1CinderPersistentVolumeSource <: SwaggerModel
    fsType::Union{ Nothing, String } # fsType
    readOnly::Union{ Nothing, Bool } # readOnly
    secretRef::Union{ Nothing, IoK8sApiCoreV1SecretReference } # secretRef
    volumeID::Union{ Nothing, String } # volumeID

    function IoK8sApiCoreV1CinderPersistentVolumeSource(;fsType=nothing, readOnly=nothing, secretRef=nothing, volumeID=nothing)
        o = new()
        set_field!(o, :fsType, fsType)
        set_field!(o, :readOnly, readOnly)
        set_field!(o, :secretRef, secretRef)
        set_field!(o, :volumeID, volumeID)
        o
    end
end # type IoK8sApiCoreV1CinderPersistentVolumeSource

const _name_map_IoK8sApiCoreV1CinderPersistentVolumeSource = Dict{String,Symbol}(["fsType"=>:fsType, "readOnly"=>:readOnly, "secretRef"=>:secretRef, "volumeID"=>:volumeID])
const _field_map_IoK8sApiCoreV1CinderPersistentVolumeSource = Dict{Symbol,String}([:fsType=>"fsType", :readOnly=>"readOnly", :secretRef=>"secretRef", :volumeID=>"volumeID"])
Swagger.name_map(::Type{ IoK8sApiCoreV1CinderPersistentVolumeSource }) = _name_map_IoK8sApiCoreV1CinderPersistentVolumeSource
Swagger.field_map(::Type{ IoK8sApiCoreV1CinderPersistentVolumeSource }) = _field_map_IoK8sApiCoreV1CinderPersistentVolumeSource

function check_required(o::IoK8sApiCoreV1CinderPersistentVolumeSource)
    (o.volumeID === nothing) && (return false)
    true
end

function validate_field(o::IoK8sApiCoreV1CinderPersistentVolumeSource, name::Symbol, val)
end
