# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList <: SwaggerModel

    function IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList

const _property_map_IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList = Dict{Symbol,Symbol}()
const _property_types_IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList = Dict{Symbol,String}()
Base.propertynames(::Type{ IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList }) = collect(keys(_property_map_IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList))
Swagger.property_type(::Type{ IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList[name]))}
Swagger.field_name(::Type{ IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList }, property_name::Symbol) =  _property_map_IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList[property_name]

function check_required(o::IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList)
    true
end

function validate_property(::Type{ IoK8sKubernetesPkgApisRbacV1alpha1ClusterRoleList }, name::Symbol, val)
end
