# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1beta1NonResourceAttributes <: SwaggerModel
    path::Nullable{ String } # path
    verb::Nullable{ String } # verb

    function V1beta1NonResourceAttributes(;path=nothing, verb=nothing)
        o = new()
        set_field!(o, :path, path)
        set_field!(o, :verb, verb)
        o
    end
end # type V1beta1NonResourceAttributes

const _name_map_V1beta1NonResourceAttributes = Dict{String,Symbol}(["path"=>:path, "verb"=>:verb])
const _field_map_V1beta1NonResourceAttributes = Dict{Symbol,String}([:path=>"path", :verb=>"verb"])
Swagger.name_map(::Type{ V1beta1NonResourceAttributes }) = _name_map_V1beta1NonResourceAttributes
Swagger.field_map(::Type{ V1beta1NonResourceAttributes }) = _field_map_V1beta1NonResourceAttributes

function check_required(o::V1beta1NonResourceAttributes)
    true
end

function validate_field(o::V1beta1NonResourceAttributes, name::Symbol, val)
end
