# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1Probe <: SwaggerModel
    failureThreshold::Nullable{ Int32 } # failureThreshold
    initialDelaySeconds::Nullable{ Int32 } # initialDelaySeconds
    periodSeconds::Nullable{ Int32 } # periodSeconds
    successThreshold::Nullable{ Int32 } # successThreshold
    timeoutSeconds::Nullable{ Int32 } # timeoutSeconds

    function V1Probe(;failureThreshold=nothing, initialDelaySeconds=nothing, periodSeconds=nothing, successThreshold=nothing, timeoutSeconds=nothing)
        o = new()
        set_field!(o, :failureThreshold, failureThreshold)
        set_field!(o, :initialDelaySeconds, initialDelaySeconds)
        set_field!(o, :periodSeconds, periodSeconds)
        set_field!(o, :successThreshold, successThreshold)
        set_field!(o, :timeoutSeconds, timeoutSeconds)
        o
    end
end # type V1Probe

const _name_map_V1Probe = Dict{String,Symbol}(["failureThreshold"=>:failureThreshold, "initialDelaySeconds"=>:initialDelaySeconds, "periodSeconds"=>:periodSeconds, "successThreshold"=>:successThreshold, "timeoutSeconds"=>:timeoutSeconds])
const _field_map_V1Probe = Dict{Symbol,String}([:failureThreshold=>"failureThreshold", :initialDelaySeconds=>"initialDelaySeconds", :periodSeconds=>"periodSeconds", :successThreshold=>"successThreshold", :timeoutSeconds=>"timeoutSeconds"])
Swagger.name_map(::Type{ V1Probe }) = _name_map_V1Probe
Swagger.field_map(::Type{ V1Probe }) = _field_map_V1Probe

function check_required(o::V1Probe)
    true
end

function validate_field(o::V1Probe, name::Symbol, val)
end
