# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sApiCoreV1LimitRangeList <: SwaggerModel
    apiVersion::Union{ Nothing, String } # apiVersion
    items::Union{ Nothing, Vector{IoK8sApiCoreV1LimitRange} } # items
    kind::Union{ Nothing, String } # kind
    metadata::Union{ Nothing, IoK8sApimachineryPkgApisMetaV1ListMeta } # metadata

    function IoK8sApiCoreV1LimitRangeList(;apiVersion=nothing, items=nothing, kind=nothing, metadata=nothing)
        o = new()
        set_field!(o, :apiVersion, apiVersion)
        set_field!(o, :items, items)
        set_field!(o, :kind, kind)
        set_field!(o, :metadata, metadata)
        o
    end
end # type IoK8sApiCoreV1LimitRangeList

const _name_map_IoK8sApiCoreV1LimitRangeList = Dict{String,Symbol}(["apiVersion"=>:apiVersion, "items"=>:items, "kind"=>:kind, "metadata"=>:metadata])
const _field_map_IoK8sApiCoreV1LimitRangeList = Dict{Symbol,String}([:apiVersion=>"apiVersion", :items=>"items", :kind=>"kind", :metadata=>"metadata"])
Swagger.name_map(::Type{ IoK8sApiCoreV1LimitRangeList }) = _name_map_IoK8sApiCoreV1LimitRangeList
Swagger.field_map(::Type{ IoK8sApiCoreV1LimitRangeList }) = _field_map_IoK8sApiCoreV1LimitRangeList

function check_required(o::IoK8sApiCoreV1LimitRangeList)
    (o.items === nothing) && (return false)
    true
end

function validate_field(o::IoK8sApiCoreV1LimitRangeList, name::Symbol, val)
end
