# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange <: SwaggerModel

    function IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange

const _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange }) = _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange }) = _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange

function check_required(o::IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisExtensionsV1beta1HostPortRange, name::Symbol, val)
end
