# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type UnversionedStatusCause <: SwaggerModel
    field::Nullable{ String } # field
    message::Nullable{ String } # message
    reason::Nullable{ String } # reason

    function UnversionedStatusCause(;field=nothing, message=nothing, reason=nothing)
        o = new()
        set_field!(o, :field, field)
        set_field!(o, :message, message)
        set_field!(o, :reason, reason)
        o
    end
end # type UnversionedStatusCause

const _name_map_UnversionedStatusCause = Dict{String,Symbol}(["field"=>:field, "message"=>:message, "reason"=>:reason])
const _field_map_UnversionedStatusCause = Dict{Symbol,String}([:field=>"field", :message=>"message", :reason=>"reason"])
Swagger.name_map(::Type{ UnversionedStatusCause }) = _name_map_UnversionedStatusCause
Swagger.field_map(::Type{ UnversionedStatusCause }) = _field_map_UnversionedStatusCause

function check_required(o::UnversionedStatusCause)
    true
end

function validate_field(o::UnversionedStatusCause, name::Symbol, val)
end
