# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus <: SwaggerModel

    function IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus

const _property_map_IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus = Dict{Symbol,Symbol}()
const _property_types_IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus = Dict{Symbol,String}()
Base.propertynames(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus }) = collect(keys(_property_map_IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus))
Swagger.property_type(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus[name]))}
Swagger.field_name(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus }, property_name::Symbol) =  _property_map_IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus[property_name]

function check_required(o::IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus)
    true
end

function validate_property(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1IngressStatus }, name::Symbol, val)
end
