# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1alpha1CertificateSigningRequestStatus <: SwaggerModel
    certificate::Nullable{ Vector{UInt8} } # certificate
    conditions::Nullable{ Vector{V1alpha1CertificateSigningRequestCondition} } # conditions

    function V1alpha1CertificateSigningRequestStatus(;certificate=nothing, conditions=nothing)
        o = new()
        set_field!(o, :certificate, certificate)
        set_field!(o, :conditions, conditions)
        o
    end
end # type V1alpha1CertificateSigningRequestStatus

const _name_map_V1alpha1CertificateSigningRequestStatus = Dict{String,Symbol}(["certificate"=>:certificate, "conditions"=>:conditions])
Swagger.name_map(::Type{ V1alpha1CertificateSigningRequestStatus }) = _name_map_V1alpha1CertificateSigningRequestStatus

function check_required(o::V1alpha1CertificateSigningRequestStatus)
    true
end

function validate_field(o::V1alpha1CertificateSigningRequestStatus, name::Symbol, val)
end
