# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sApiBatchV1beta1CronJobSpec <: SwaggerModel
    concurrencyPolicy::Union{ Nothing, String } # concurrencyPolicy
    failedJobsHistoryLimit::Union{ Nothing, Int32 } # failedJobsHistoryLimit
    jobTemplate::Union{ Nothing, IoK8sApiBatchV1beta1JobTemplateSpec } # jobTemplate
    schedule::Union{ Nothing, String } # schedule
    startingDeadlineSeconds::Union{ Nothing, Int64 } # startingDeadlineSeconds
    successfulJobsHistoryLimit::Union{ Nothing, Int32 } # successfulJobsHistoryLimit
    suspend::Union{ Nothing, Bool } # suspend

    function IoK8sApiBatchV1beta1CronJobSpec(;concurrencyPolicy=nothing, failedJobsHistoryLimit=nothing, jobTemplate=nothing, schedule=nothing, startingDeadlineSeconds=nothing, successfulJobsHistoryLimit=nothing, suspend=nothing)
        o = new()
        set_field!(o, :concurrencyPolicy, concurrencyPolicy)
        set_field!(o, :failedJobsHistoryLimit, failedJobsHistoryLimit)
        set_field!(o, :jobTemplate, jobTemplate)
        set_field!(o, :schedule, schedule)
        set_field!(o, :startingDeadlineSeconds, startingDeadlineSeconds)
        set_field!(o, :successfulJobsHistoryLimit, successfulJobsHistoryLimit)
        set_field!(o, :suspend, suspend)
        o
    end
end # type IoK8sApiBatchV1beta1CronJobSpec

const _name_map_IoK8sApiBatchV1beta1CronJobSpec = Dict{String,Symbol}(["concurrencyPolicy"=>:concurrencyPolicy, "failedJobsHistoryLimit"=>:failedJobsHistoryLimit, "jobTemplate"=>:jobTemplate, "schedule"=>:schedule, "startingDeadlineSeconds"=>:startingDeadlineSeconds, "successfulJobsHistoryLimit"=>:successfulJobsHistoryLimit, "suspend"=>:suspend])
const _field_map_IoK8sApiBatchV1beta1CronJobSpec = Dict{Symbol,String}([:concurrencyPolicy=>"concurrencyPolicy", :failedJobsHistoryLimit=>"failedJobsHistoryLimit", :jobTemplate=>"jobTemplate", :schedule=>"schedule", :startingDeadlineSeconds=>"startingDeadlineSeconds", :successfulJobsHistoryLimit=>"successfulJobsHistoryLimit", :suspend=>"suspend"])
Swagger.name_map(::Type{ IoK8sApiBatchV1beta1CronJobSpec }) = _name_map_IoK8sApiBatchV1beta1CronJobSpec
Swagger.field_map(::Type{ IoK8sApiBatchV1beta1CronJobSpec }) = _field_map_IoK8sApiBatchV1beta1CronJobSpec

function check_required(o::IoK8sApiBatchV1beta1CronJobSpec)
    (o.jobTemplate === nothing) && (return false)
    (o.schedule === nothing) && (return false)
    true
end

function validate_field(o::IoK8sApiBatchV1beta1CronJobSpec, name::Symbol, val)
end
