# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sApiCoreV1NodeSelector <: SwaggerModel
    nodeSelectorTerms::Union{ Nothing, Vector{IoK8sApiCoreV1NodeSelectorTerm} } # nodeSelectorTerms

    function IoK8sApiCoreV1NodeSelector(;nodeSelectorTerms=nothing)
        o = new()
        set_field!(o, :nodeSelectorTerms, nodeSelectorTerms)
        o
    end
end # type IoK8sApiCoreV1NodeSelector

const _name_map_IoK8sApiCoreV1NodeSelector = Dict{String,Symbol}(["nodeSelectorTerms"=>:nodeSelectorTerms])
const _field_map_IoK8sApiCoreV1NodeSelector = Dict{Symbol,String}([:nodeSelectorTerms=>"nodeSelectorTerms"])
Swagger.name_map(::Type{ IoK8sApiCoreV1NodeSelector }) = _name_map_IoK8sApiCoreV1NodeSelector
Swagger.field_map(::Type{ IoK8sApiCoreV1NodeSelector }) = _field_map_IoK8sApiCoreV1NodeSelector

function check_required(o::IoK8sApiCoreV1NodeSelector)
    (o.nodeSelectorTerms === nothing) && (return false)
    true
end

function validate_field(o::IoK8sApiCoreV1NodeSelector, name::Symbol, val)
end
