# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec <: SwaggerModel

    function IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec

const _name_map_IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec }) = _name_map_IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec }) = _field_map_IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec

function check_required(o::IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec, name::Symbol, val)
end
