# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApisBatchV1JobList <: SwaggerModel

    function IoK8sKubernetesPkgApisBatchV1JobList(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisBatchV1JobList

const _name_map_IoK8sKubernetesPkgApisBatchV1JobList = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisBatchV1JobList = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisBatchV1JobList }) = _name_map_IoK8sKubernetesPkgApisBatchV1JobList
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisBatchV1JobList }) = _field_map_IoK8sKubernetesPkgApisBatchV1JobList

function check_required(o::IoK8sKubernetesPkgApisBatchV1JobList)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisBatchV1JobList, name::Symbol, val)
end
