# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct IoK8sApiCoreV1Taint <: SwaggerModel
    effect::Any # spec type: Union{ Nothing, String } # spec name: effect
    key::Any # spec type: Union{ Nothing, String } # spec name: key
    timeAdded::Any # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1Time } # spec name: timeAdded
    value::Any # spec type: Union{ Nothing, String } # spec name: value

    function IoK8sApiCoreV1Taint(;effect=nothing, key=nothing, timeAdded=nothing, value=nothing)
        o = new()
        validate_property(IoK8sApiCoreV1Taint, Symbol("effect"), effect)
        setfield!(o, Symbol("effect"), effect)
        validate_property(IoK8sApiCoreV1Taint, Symbol("key"), key)
        setfield!(o, Symbol("key"), key)
        validate_property(IoK8sApiCoreV1Taint, Symbol("timeAdded"), timeAdded)
        setfield!(o, Symbol("timeAdded"), timeAdded)
        validate_property(IoK8sApiCoreV1Taint, Symbol("value"), value)
        setfield!(o, Symbol("value"), value)
        o
    end
end # type IoK8sApiCoreV1Taint

const _property_map_IoK8sApiCoreV1Taint = Dict{Symbol,Symbol}(Symbol("effect")=>Symbol("effect"), Symbol("key")=>Symbol("key"), Symbol("timeAdded")=>Symbol("timeAdded"), Symbol("value")=>Symbol("value"))
const _property_types_IoK8sApiCoreV1Taint = Dict{Symbol,String}(Symbol("effect")=>"String", Symbol("key")=>"String", Symbol("timeAdded")=>"IoK8sApimachineryPkgApisMetaV1Time", Symbol("value")=>"String")
Base.propertynames(::Type{ IoK8sApiCoreV1Taint }) = collect(keys(_property_map_IoK8sApiCoreV1Taint))
Swagger.property_type(::Type{ IoK8sApiCoreV1Taint }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_IoK8sApiCoreV1Taint[name]))}
Swagger.field_name(::Type{ IoK8sApiCoreV1Taint }, property_name::Symbol) =  _property_map_IoK8sApiCoreV1Taint[property_name]

function check_required(o::IoK8sApiCoreV1Taint)
    (getproperty(o, Symbol("effect")) === nothing) && (return false)
    (getproperty(o, Symbol("key")) === nothing) && (return false)
    true
end

function validate_property(::Type{ IoK8sApiCoreV1Taint }, name::Symbol, val)
end
