# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct IoK8sApimachineryPkgApisMetaV1FieldsV1 <: SwaggerModel

    function IoK8sApimachineryPkgApisMetaV1FieldsV1(;)
        o = new()
        o
    end
end # type IoK8sApimachineryPkgApisMetaV1FieldsV1

const _property_map_IoK8sApimachineryPkgApisMetaV1FieldsV1 = Dict{Symbol,Symbol}()
const _property_types_IoK8sApimachineryPkgApisMetaV1FieldsV1 = Dict{Symbol,String}()
Base.propertynames(::Type{ IoK8sApimachineryPkgApisMetaV1FieldsV1 }) = collect(keys(_property_map_IoK8sApimachineryPkgApisMetaV1FieldsV1))
Swagger.property_type(::Type{ IoK8sApimachineryPkgApisMetaV1FieldsV1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApimachineryPkgApisMetaV1FieldsV1[name]))}
Swagger.field_name(::Type{ IoK8sApimachineryPkgApisMetaV1FieldsV1 }, property_name::Symbol) =  _property_map_IoK8sApimachineryPkgApisMetaV1FieldsV1[property_name]

function check_required(o::IoK8sApimachineryPkgApisMetaV1FieldsV1)
    true
end

function validate_property(::Type{ IoK8sApimachineryPkgApisMetaV1FieldsV1 }, name::Symbol, val)
end
