# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApiV1LocalVolumeSource <: SwaggerModel

    function IoK8sKubernetesPkgApiV1LocalVolumeSource(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1LocalVolumeSource

const _name_map_IoK8sKubernetesPkgApiV1LocalVolumeSource = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApiV1LocalVolumeSource = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApiV1LocalVolumeSource }) = _name_map_IoK8sKubernetesPkgApiV1LocalVolumeSource
Swagger.field_map(::Type{ IoK8sKubernetesPkgApiV1LocalVolumeSource }) = _field_map_IoK8sKubernetesPkgApiV1LocalVolumeSource

function check_required(o::IoK8sKubernetesPkgApiV1LocalVolumeSource)
    true
end

function validate_field(o::IoK8sKubernetesPkgApiV1LocalVolumeSource, name::Symbol, val)
end
