# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct IoK8sKubernetesPkgApiV1ContainerImage <: SwaggerModel

    function IoK8sKubernetesPkgApiV1ContainerImage(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1ContainerImage

const _property_map_IoK8sKubernetesPkgApiV1ContainerImage = Dict{Symbol,Symbol}()
const _property_types_IoK8sKubernetesPkgApiV1ContainerImage = Dict{Symbol,String}()
Base.propertynames(::Type{ IoK8sKubernetesPkgApiV1ContainerImage }) = collect(keys(_property_map_IoK8sKubernetesPkgApiV1ContainerImage))
Swagger.property_type(::Type{ IoK8sKubernetesPkgApiV1ContainerImage }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_IoK8sKubernetesPkgApiV1ContainerImage[name]))}
Swagger.field_name(::Type{ IoK8sKubernetesPkgApiV1ContainerImage }, property_name::Symbol) =  _property_map_IoK8sKubernetesPkgApiV1ContainerImage[property_name]

function check_required(o::IoK8sKubernetesPkgApiV1ContainerImage)
    true
end

function validate_property(::Type{ IoK8sKubernetesPkgApiV1ContainerImage }, name::Symbol, val)
end
