# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS <: SwaggerModel

    function IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS

const _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS }) = _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS }) = _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS

function check_required(o::IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisExtensionsV1beta1IngressTLS, name::Symbol, val)
end
