# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sApiRbacV1beta1RoleBindingList <: SwaggerModel
    apiVersion::Union{ Nothing, String } # apiVersion
    items::Union{ Nothing, Vector{IoK8sApiRbacV1beta1RoleBinding} } # items
    kind::Union{ Nothing, String } # kind
    metadata::Union{ Nothing, IoK8sApimachineryPkgApisMetaV1ListMeta } # metadata

    function IoK8sApiRbacV1beta1RoleBindingList(;apiVersion=nothing, items=nothing, kind=nothing, metadata=nothing)
        o = new()
        set_field!(o, :apiVersion, apiVersion)
        set_field!(o, :items, items)
        set_field!(o, :kind, kind)
        set_field!(o, :metadata, metadata)
        o
    end
end # type IoK8sApiRbacV1beta1RoleBindingList

const _name_map_IoK8sApiRbacV1beta1RoleBindingList = Dict{String,Symbol}(["apiVersion"=>:apiVersion, "items"=>:items, "kind"=>:kind, "metadata"=>:metadata])
const _field_map_IoK8sApiRbacV1beta1RoleBindingList = Dict{Symbol,String}([:apiVersion=>"apiVersion", :items=>"items", :kind=>"kind", :metadata=>"metadata"])
Swagger.name_map(::Type{ IoK8sApiRbacV1beta1RoleBindingList }) = _name_map_IoK8sApiRbacV1beta1RoleBindingList
Swagger.field_map(::Type{ IoK8sApiRbacV1beta1RoleBindingList }) = _field_map_IoK8sApiRbacV1beta1RoleBindingList

function check_required(o::IoK8sApiRbacV1beta1RoleBindingList)
    (o.items === nothing) && (return false)
    true
end

function validate_field(o::IoK8sApiRbacV1beta1RoleBindingList, name::Symbol, val)
end
