# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig <: SwaggerModel

    function IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig

const _name_map_IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig }) = _name_map_IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig }) = _field_map_IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig

function check_required(o::IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisAdmissionregistrationV1alpha1AdmissionHookClientConfig, name::Symbol, val)
end
