# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct IoK8sKubernetesPkgApiV1ReplicationControllerSpec <: SwaggerModel

    function IoK8sKubernetesPkgApiV1ReplicationControllerSpec(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1ReplicationControllerSpec

const _property_map_IoK8sKubernetesPkgApiV1ReplicationControllerSpec = Dict{Symbol,Symbol}()
const _property_types_IoK8sKubernetesPkgApiV1ReplicationControllerSpec = Dict{Symbol,String}()
Base.propertynames(::Type{ IoK8sKubernetesPkgApiV1ReplicationControllerSpec }) = collect(keys(_property_map_IoK8sKubernetesPkgApiV1ReplicationControllerSpec))
Swagger.property_type(::Type{ IoK8sKubernetesPkgApiV1ReplicationControllerSpec }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_IoK8sKubernetesPkgApiV1ReplicationControllerSpec[name]))}
Swagger.field_name(::Type{ IoK8sKubernetesPkgApiV1ReplicationControllerSpec }, property_name::Symbol) =  _property_map_IoK8sKubernetesPkgApiV1ReplicationControllerSpec[property_name]

function check_required(o::IoK8sKubernetesPkgApiV1ReplicationControllerSpec)
    true
end

function validate_property(::Type{ IoK8sKubernetesPkgApiV1ReplicationControllerSpec }, name::Symbol, val)
end
