# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec <: SwaggerModel

    function IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec

const _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec }) = _name_map_IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec }) = _field_map_IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec

function check_required(o::IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisExtensionsV1beta1ScaleSpec, name::Symbol, val)
end
