# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus <: SwaggerModel

    function IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus

const _name_map_IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus }) = _name_map_IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus }) = _field_map_IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus

function check_required(o::IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReviewStatus, name::Symbol, val)
end
