# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement <: SwaggerModel
    key::Any # spec type: Union{ Nothing, String } # spec name: key
    operator::Any # spec type: Union{ Nothing, String } # spec name: operator
    values::Any # spec type: Union{ Nothing, Vector{String} } # spec name: values

    function IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement(;key=nothing, operator=nothing, values=nothing)
        o = new()
        validate_property(IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement, Symbol("key"), key)
        setfield!(o, Symbol("key"), key)
        validate_property(IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement, Symbol("operator"), operator)
        setfield!(o, Symbol("operator"), operator)
        validate_property(IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement, Symbol("values"), values)
        setfield!(o, Symbol("values"), values)
        o
    end
end # type IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement

const _property_map_IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement = Dict{Symbol,Symbol}(Symbol("key")=>Symbol("key"), Symbol("operator")=>Symbol("operator"), Symbol("values")=>Symbol("values"))
const _property_types_IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement = Dict{Symbol,String}(Symbol("key")=>"String", Symbol("operator")=>"String", Symbol("values")=>"Vector{String}")
Base.propertynames(::Type{ IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement }) = collect(keys(_property_map_IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement))
Swagger.property_type(::Type{ IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement[name]))}
Swagger.field_name(::Type{ IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement }, property_name::Symbol) =  _property_map_IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement[property_name]

function check_required(o::IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement)
    (getproperty(o, Symbol("key")) === nothing) && (return false)
    (getproperty(o, Symbol("operator")) === nothing) && (return false)
    true
end

function validate_property(::Type{ IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement }, name::Symbol, val)
end
