# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule <: SwaggerModel

    function IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule

const _name_map_IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule }) = _name_map_IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule }) = _field_map_IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule

function check_required(o::IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisNetworkingV1NetworkPolicyIngressRule, name::Symbol, val)
end
