# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""LimitResponse defines how to handle requests that can not be executed right now.

    IoK8sApiFlowcontrolV1alpha1LimitResponse(;
        queuing=nothing,
        type=nothing,
    )

    - queuing::IoK8sApiFlowcontrolV1alpha1QueuingConfiguration : &#x60;queuing&#x60; holds the configuration parameters for queuing. This field may be non-empty only if &#x60;type&#x60; is &#x60;\&quot;Queue\&quot;&#x60;.
    - type::String : &#x60;type&#x60; is \&quot;Queue\&quot; or \&quot;Reject\&quot;. \&quot;Queue\&quot; means that requests that can not be executed upon arrival are held in a queue until they can be executed or a queuing limit is reached. \&quot;Reject\&quot; means that requests that can not be executed upon arrival are rejected. Required.
"""
mutable struct IoK8sApiFlowcontrolV1alpha1LimitResponse <: SwaggerModel
    queuing::Any # spec type: Union{ Nothing, IoK8sApiFlowcontrolV1alpha1QueuingConfiguration } # spec name: queuing
    type::Any # spec type: Union{ Nothing, String } # spec name: type

    function IoK8sApiFlowcontrolV1alpha1LimitResponse(;queuing=nothing, type=nothing)
        o = new()
        validate_property(IoK8sApiFlowcontrolV1alpha1LimitResponse, Symbol("queuing"), queuing)
        setfield!(o, Symbol("queuing"), queuing)
        validate_property(IoK8sApiFlowcontrolV1alpha1LimitResponse, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        o
    end
end # type IoK8sApiFlowcontrolV1alpha1LimitResponse

const _property_map_IoK8sApiFlowcontrolV1alpha1LimitResponse = Dict{Symbol,Symbol}(Symbol("queuing")=>Symbol("queuing"), Symbol("type")=>Symbol("type"))
const _property_types_IoK8sApiFlowcontrolV1alpha1LimitResponse = Dict{Symbol,String}(Symbol("queuing")=>"IoK8sApiFlowcontrolV1alpha1QueuingConfiguration", Symbol("type")=>"String")
Base.propertynames(::Type{ IoK8sApiFlowcontrolV1alpha1LimitResponse }) = collect(keys(_property_map_IoK8sApiFlowcontrolV1alpha1LimitResponse))
Swagger.property_type(::Type{ IoK8sApiFlowcontrolV1alpha1LimitResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiFlowcontrolV1alpha1LimitResponse[name]))}
Swagger.field_name(::Type{ IoK8sApiFlowcontrolV1alpha1LimitResponse }, property_name::Symbol) =  _property_map_IoK8sApiFlowcontrolV1alpha1LimitResponse[property_name]

function check_required(o::IoK8sApiFlowcontrolV1alpha1LimitResponse)
    (getproperty(o, Symbol("type")) === nothing) && (return false)
    true
end

function validate_property(::Type{ IoK8sApiFlowcontrolV1alpha1LimitResponse }, name::Symbol, val)
end
