# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApiV1EventSource <: SwaggerModel

    function IoK8sKubernetesPkgApiV1EventSource(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1EventSource

const _name_map_IoK8sKubernetesPkgApiV1EventSource = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApiV1EventSource = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApiV1EventSource }) = _name_map_IoK8sKubernetesPkgApiV1EventSource
Swagger.field_map(::Type{ IoK8sKubernetesPkgApiV1EventSource }) = _field_map_IoK8sKubernetesPkgApiV1EventSource

function check_required(o::IoK8sKubernetesPkgApiV1EventSource)
    true
end

function validate_field(o::IoK8sKubernetesPkgApiV1EventSource, name::Symbol, val)
end
