# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApiV1LoadBalancerStatus <: SwaggerModel

    function IoK8sKubernetesPkgApiV1LoadBalancerStatus(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1LoadBalancerStatus

const _name_map_IoK8sKubernetesPkgApiV1LoadBalancerStatus = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApiV1LoadBalancerStatus = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApiV1LoadBalancerStatus }) = _name_map_IoK8sKubernetesPkgApiV1LoadBalancerStatus
Swagger.field_map(::Type{ IoK8sKubernetesPkgApiV1LoadBalancerStatus }) = _field_map_IoK8sKubernetesPkgApiV1LoadBalancerStatus

function check_required(o::IoK8sKubernetesPkgApiV1LoadBalancerStatus)
    true
end

function validate_field(o::IoK8sKubernetesPkgApiV1LoadBalancerStatus, name::Symbol, val)
end
