# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApiV1AzureDiskVolumeSource <: SwaggerModel

    function IoK8sKubernetesPkgApiV1AzureDiskVolumeSource(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1AzureDiskVolumeSource

const _name_map_IoK8sKubernetesPkgApiV1AzureDiskVolumeSource = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApiV1AzureDiskVolumeSource = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApiV1AzureDiskVolumeSource }) = _name_map_IoK8sKubernetesPkgApiV1AzureDiskVolumeSource
Swagger.field_map(::Type{ IoK8sKubernetesPkgApiV1AzureDiskVolumeSource }) = _field_map_IoK8sKubernetesPkgApiV1AzureDiskVolumeSource

function check_required(o::IoK8sKubernetesPkgApiV1AzureDiskVolumeSource)
    true
end

function validate_field(o::IoK8sKubernetesPkgApiV1AzureDiskVolumeSource, name::Symbol, val)
end
