# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApiV1ReplicationControllerCondition <: SwaggerModel

    function IoK8sKubernetesPkgApiV1ReplicationControllerCondition(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApiV1ReplicationControllerCondition

const _name_map_IoK8sKubernetesPkgApiV1ReplicationControllerCondition = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApiV1ReplicationControllerCondition = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApiV1ReplicationControllerCondition }) = _name_map_IoK8sKubernetesPkgApiV1ReplicationControllerCondition
Swagger.field_map(::Type{ IoK8sKubernetesPkgApiV1ReplicationControllerCondition }) = _field_map_IoK8sKubernetesPkgApiV1ReplicationControllerCondition

function check_required(o::IoK8sKubernetesPkgApiV1ReplicationControllerCondition)
    true
end

function validate_field(o::IoK8sKubernetesPkgApiV1ReplicationControllerCondition, name::Symbol, val)
end
