# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct IoK8sKubernetesPkgApisPolicyV1beta1Eviction <: SwaggerModel

    function IoK8sKubernetesPkgApisPolicyV1beta1Eviction(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisPolicyV1beta1Eviction

const _name_map_IoK8sKubernetesPkgApisPolicyV1beta1Eviction = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisPolicyV1beta1Eviction = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisPolicyV1beta1Eviction }) = _name_map_IoK8sKubernetesPkgApisPolicyV1beta1Eviction
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisPolicyV1beta1Eviction }) = _field_map_IoK8sKubernetesPkgApisPolicyV1beta1Eviction

function check_required(o::IoK8sKubernetesPkgApisPolicyV1beta1Eviction)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisPolicyV1beta1Eviction, name::Symbol, val)
end
