# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type IoK8sKubernetesPkgApisAutoscalingV1Scale <: SwaggerModel

    function IoK8sKubernetesPkgApisAutoscalingV1Scale(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisAutoscalingV1Scale

const _name_map_IoK8sKubernetesPkgApisAutoscalingV1Scale = Dict{String,Symbol}([])
const _field_map_IoK8sKubernetesPkgApisAutoscalingV1Scale = Dict{Symbol,String}([])
Swagger.name_map(::Type{ IoK8sKubernetesPkgApisAutoscalingV1Scale }) = _name_map_IoK8sKubernetesPkgApisAutoscalingV1Scale
Swagger.field_map(::Type{ IoK8sKubernetesPkgApisAutoscalingV1Scale }) = _field_map_IoK8sKubernetesPkgApisAutoscalingV1Scale

function check_required(o::IoK8sKubernetesPkgApisAutoscalingV1Scale)
    true
end

function validate_field(o::IoK8sKubernetesPkgApisAutoscalingV1Scale, name::Symbol, val)
end
