# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.



mutable struct IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList <: SwaggerModel

    function IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList(;)
        o = new()
        o
    end
end # type IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList

const _property_map_IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList = Dict{Symbol,Symbol}()
const _property_types_IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList = Dict{Symbol,String}()
Base.propertynames(::Type{ IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList }) = collect(keys(_property_map_IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList))
Swagger.property_type(::Type{ IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList }, name::Symbol) = Union{Nothing,eval(Meta.parse(_property_types_IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList[name]))}
Swagger.field_name(::Type{ IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList }, property_name::Symbol) =  _property_map_IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList[property_name]

function check_required(o::IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList)
    true
end

function validate_property(::Type{ IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList }, name::Symbol, val)
end
