# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).

    IoK8sApiAutoscalingV2beta2ExternalMetricSource(;
        metric=nothing,
        target=nothing,
    )

    - metric::IoK8sApiAutoscalingV2beta2MetricIdentifier : metric identifies the target metric by name and selector
    - target::IoK8sApiAutoscalingV2beta2MetricTarget : target specifies the target value for the given metric
"""
mutable struct IoK8sApiAutoscalingV2beta2ExternalMetricSource <: SwaggerModel
    metric::Any # spec type: Union{ Nothing, IoK8sApiAutoscalingV2beta2MetricIdentifier } # spec name: metric
    target::Any # spec type: Union{ Nothing, IoK8sApiAutoscalingV2beta2MetricTarget } # spec name: target

    function IoK8sApiAutoscalingV2beta2ExternalMetricSource(;metric=nothing, target=nothing)
        o = new()
        validate_property(IoK8sApiAutoscalingV2beta2ExternalMetricSource, Symbol("metric"), metric)
        setfield!(o, Symbol("metric"), metric)
        validate_property(IoK8sApiAutoscalingV2beta2ExternalMetricSource, Symbol("target"), target)
        setfield!(o, Symbol("target"), target)
        o
    end
end # type IoK8sApiAutoscalingV2beta2ExternalMetricSource

const _property_map_IoK8sApiAutoscalingV2beta2ExternalMetricSource = Dict{Symbol,Symbol}(Symbol("metric")=>Symbol("metric"), Symbol("target")=>Symbol("target"))
const _property_types_IoK8sApiAutoscalingV2beta2ExternalMetricSource = Dict{Symbol,String}(Symbol("metric")=>"IoK8sApiAutoscalingV2beta2MetricIdentifier", Symbol("target")=>"IoK8sApiAutoscalingV2beta2MetricTarget")
Base.propertynames(::Type{ IoK8sApiAutoscalingV2beta2ExternalMetricSource }) = collect(keys(_property_map_IoK8sApiAutoscalingV2beta2ExternalMetricSource))
Swagger.property_type(::Type{ IoK8sApiAutoscalingV2beta2ExternalMetricSource }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiAutoscalingV2beta2ExternalMetricSource[name]))}
Swagger.field_name(::Type{ IoK8sApiAutoscalingV2beta2ExternalMetricSource }, property_name::Symbol) =  _property_map_IoK8sApiAutoscalingV2beta2ExternalMetricSource[property_name]

function check_required(o::IoK8sApiAutoscalingV2beta2ExternalMetricSource)
    (getproperty(o, Symbol("metric")) === nothing) && (return false)
    (getproperty(o, Symbol("target")) === nothing) && (return false)
    true
end

function validate_property(::Type{ IoK8sApiAutoscalingV2beta2ExternalMetricSource }, name::Symbol, val)
end
