# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1beta1TokenReviewStatus <: SwaggerModel
    authenticated::Nullable{ Bool } # authenticated
    error::Nullable{ String } # error
    user::Nullable{ V1beta1UserInfo } # user

    function V1beta1TokenReviewStatus(;authenticated=nothing, error=nothing, user=nothing)
        o = new()
        set_field!(o, :authenticated, authenticated)
        set_field!(o, :error, error)
        set_field!(o, :user, user)
        o
    end
end # type V1beta1TokenReviewStatus

const _name_map_V1beta1TokenReviewStatus = Dict{String,Symbol}(["authenticated"=>:authenticated, "error"=>:error, "user"=>:user])
Swagger.name_map(::Type{ V1beta1TokenReviewStatus }) = _name_map_V1beta1TokenReviewStatus

function check_required(o::V1beta1TokenReviewStatus)
    true
end

function validate_field(o::V1beta1TokenReviewStatus, name::Symbol, val)
end
