# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1TCPSocketAction
    port::Nullable{ IntstrIntOrString } # port

    function V1TCPSocketAction(;port=nothing)
        o = new()
        set_field!(o, :port, port)
        o
    end
end # type V1TCPSocketAction

const _name_map_V1TCPSocketAction = Dict{String,Symbol}(["port"=>:port])
Swagger.name_map(::Type{ V1TCPSocketAction }) = _name_map_V1TCPSocketAction

function check_required(o::V1TCPSocketAction)
    isnull(o.port) && (return false)
    true
end

function set_field!(o::V1TCPSocketAction, name::Symbol, val)
    setfield!(o, name, fieldtype(V1TCPSocketAction,name)(val))
end

convert(::Type{ V1TCPSocketAction }, json::Dict{String,Any}) = Swagger.from_json(V1TCPSocketAction, json)
