# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1beta1APIVersion <: SwaggerModel
    name::Nullable{ String } # name

    function V1beta1APIVersion(;name=nothing)
        o = new()
        set_field!(o, :name, name)
        o
    end
end # type V1beta1APIVersion

const _name_map_V1beta1APIVersion = Dict{String,Symbol}(["name"=>:name])
Swagger.name_map(::Type{ V1beta1APIVersion }) = _name_map_V1beta1APIVersion

function check_required(o::V1beta1APIVersion)
    true
end

function validate_field(o::V1beta1APIVersion, name::Symbol, val)
end
