# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type UnversionedStatusDetails
    causes::Nullable{ Vector{UnversionedStatusCause} } # causes
    group::Nullable{ String } # group
    kind::Nullable{ String } # kind
    name::Nullable{ String } # name
    retryAfterSeconds::Nullable{ Int32 } # retryAfterSeconds

    function UnversionedStatusDetails(;causes=nothing, group=nothing, kind=nothing, name=nothing, retryAfterSeconds=nothing)
        o = new()
        set_field!(o, :causes, causes)
        set_field!(o, :group, group)
        set_field!(o, :kind, kind)
        set_field!(o, :name, name)
        set_field!(o, :retryAfterSeconds, retryAfterSeconds)
        o
    end
end # type UnversionedStatusDetails

const _name_map_UnversionedStatusDetails = Dict{String,Symbol}(["causes"=>:causes, "group"=>:group, "kind"=>:kind, "name"=>:name, "retryAfterSeconds"=>:retryAfterSeconds])
Swagger.name_map(::Type{ UnversionedStatusDetails }) = _name_map_UnversionedStatusDetails

function check_required(o::UnversionedStatusDetails)
    true
end

function set_field!(o::UnversionedStatusDetails, name::Symbol, val)
    setfield!(o, name, fieldtype(UnversionedStatusDetails,name)(val))
end

convert(::Type{ UnversionedStatusDetails }, json::Dict{String,Any}) = Swagger.from_json(UnversionedStatusDetails, json)
