# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1ServiceList
    items::Nullable{ Vector{V1Service} } # items
    metadata::Nullable{ UnversionedListMeta } # metadata

    function V1ServiceList(;items=nothing, metadata=nothing)
        o = new()
        set_field!(o, :items, items)
        set_field!(o, :metadata, metadata)
        o
    end
end # type V1ServiceList

const _name_map_V1ServiceList = Dict{String,Symbol}(["items"=>:items, "metadata"=>:metadata])
Swagger.name_map(::Type{ V1ServiceList }) = _name_map_V1ServiceList

function check_required(o::V1ServiceList)
    isnull(o.items) && (return false)
    true
end

function set_field!(o::V1ServiceList, name::Symbol, val)
    setfield!(o, name, fieldtype(V1ServiceList,name)(val))
end

convert(::Type{ V1ServiceList }, json::Dict{String,Any}) = Swagger.from_json(V1ServiceList, json)
