# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1PersistentVolumeStatus
    message::Nullable{ String } # message
    phase::Nullable{ String } # phase
    reason::Nullable{ String } # reason

    function V1PersistentVolumeStatus(;message=nothing, phase=nothing, reason=nothing)
        o = new()
        set_field!(o, :message, message)
        set_field!(o, :phase, phase)
        set_field!(o, :reason, reason)
        o
    end
end # type V1PersistentVolumeStatus

const _name_map_V1PersistentVolumeStatus = Dict{String,Symbol}(["message"=>:message, "phase"=>:phase, "reason"=>:reason])
Swagger.name_map(::Type{ V1PersistentVolumeStatus }) = _name_map_V1PersistentVolumeStatus

function check_required(o::V1PersistentVolumeStatus)
    true
end

function set_field!(o::V1PersistentVolumeStatus, name::Symbol, val)
    setfield!(o, name, fieldtype(V1PersistentVolumeStatus,name)(val))
end

convert(::Type{ V1PersistentVolumeStatus }, json::Dict{String,Any}) = Swagger.from_json(V1PersistentVolumeStatus, json)
