# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1beta1JobList
    items::Nullable{ Vector{V1beta1Job} } # items
    metadata::Nullable{ UnversionedListMeta } # metadata

    function V1beta1JobList(;items=nothing, metadata=nothing)
        o = new()
        set_field!(o, :items, items)
        set_field!(o, :metadata, metadata)
        o
    end
end # type V1beta1JobList

const _name_map_V1beta1JobList = Dict{String,Symbol}(["items"=>:items, "metadata"=>:metadata])
Swagger.name_map(::Type{ V1beta1JobList }) = _name_map_V1beta1JobList

function check_required(o::V1beta1JobList)
    isnull(o.items) && (return false)
    true
end

function set_field!(o::V1beta1JobList, name::Symbol, val)
    setfield!(o, name, fieldtype(V1beta1JobList,name)(val))
end

convert(::Type{ V1beta1JobList }, json::Dict{String,Any}) = Swagger.from_json(V1beta1JobList, json)
