# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

type V1PodTemplate
    metadata::Nullable{ V1ObjectMeta } # metadata
    template::Nullable{ V1PodTemplateSpec } # template

    function V1PodTemplate(;metadata=nothing, template=nothing)
        o = new()
        set_field!(o, :metadata, metadata)
        set_field!(o, :template, template)
        o
    end
end # type V1PodTemplate

const _name_map_V1PodTemplate = Dict{String,Symbol}(["metadata"=>:metadata, "template"=>:template])
Swagger.name_map(::Type{ V1PodTemplate }) = _name_map_V1PodTemplate

function check_required(o::V1PodTemplate)
    true
end

function set_field!(o::V1PodTemplate, name::Symbol, val)
    setfield!(o, name, fieldtype(V1PodTemplate,name)(val))
end

convert(::Type{ V1PodTemplate }, json::Dict{String,Any}) = Swagger.from_json(V1PodTemplate, json)
