# simple Julia APIs over Kubernetes Swagger interface

# TODO: Deployment
get(ctx::KuberContext, ::Type{ComponentStatus}) = listCoreV1ComponentStatus(ctx.api)
get(ctx::KuberContext, ::Type{ComponentStatus}, compname::String) = readCoreV1ComponentStatus(ctx.api, compname)
get(ctx::KuberContext, ::Type{Namespace}) = listCoreV1Namespace(ctx.api)
get(ctx::KuberContext, ::Type{Endpoints}) = listCoreV1EndpointsForAllNamespaces(ctx.api)
get(ctx::KuberContext, ::Type{Pod}) = listCoreV1NamespacedPod(ctx.api, ctx.namespace)
get(ctx::KuberContext, ::Type{PodTemplate}) = listCoreV1NamespacedPodTemplate(ctx.api, ctx.namespace)
get(ctx::KuberContext, ::Type{ReplicationController}) = listCoreV1NamespacedReplicationController(ctx.api, ctx.namespace)
get(ctx::KuberContext, ::Type{Service}) = listCoreV1NamespacedService(ctx.api, ctx.namespace)
get(ctx::KuberContext, ::Type{PersistentVolume}) = listCoreV1PersistentVolume(ctx.api)
get(ctx::KuberContext, ::Type{PersistentVolumeClaim}) = listCoreV1NamespacedPersistentVolumeClaim(ctx.api, ctx.namespace)

put!(ctx::KuberContext, ns::Namespace) = createCoreV1Namespace(ctx.api, ns)
put!(ctx::KuberContext, epts::Endpoints) = createCoreV1NamespacedEndpoints(ctx.api, ctx.namespace, epts)
put!(ctx::KuberContext, pod::Pod) = createCoreV1NamespacedPod(ctx.api, ctx.namespace, pod)
put!(ctx::KuberContext, pt::PodTemplate) = createCoreV1NamespacedPodTemplate(ctx.api, ctx.namespace, pt)
put!(ctx::KuberContext, rc::ReplicationController) = createCoreV1NamespacedReplicationController(ctx.api, ctx.namespace, rc)
put!(ctx::KuberContext, svc::Service) = createCoreV1NamespacedService(ctx.api, ctx.namespace, svc)
put!(ctx::KuberContext, pv::PersistentVolume) = createCoreV1PersistentVolume(ctx.api, pv)
put!(ctx::KuberContext, pvc::PersistentVolumeClaim) = createCoreV1NamespacedPersistentVolumeClaim(ctx.api, ctx.namespace, pvc)

put!(ctx::KuberContext, ::Type{Namespace}, ns::Dict{String,Any}) = createCoreV1Namespace(ctx.api, ns)
put!(ctx::KuberContext, ::Type{Endpoints}, epts::Dict{String,Any}) = createCoreV1NamespacedEndpoints(ctx.api, ctx.namespace, epts)
put!(ctx::KuberContext, ::Type{Pod}, pod::Dict{String,Any}) = createCoreV1NamespacedPod(ctx.api, ctx.namespace, pod)
put!(ctx::KuberContext, ::Type{PodTemplate}, pt::Dict{String,Any}) = createCoreV1NamespacedPodTemplate(ctx.api, ctx.namespace, pt)
put!(ctx::KuberContext, ::Type{ReplicationController}, rc::Dict{String,Any}) = createCoreV1NamespacedReplicationController(ctx.api, ctx.namespace, rc)
put!(ctx::KuberContext, ::Type{Service}, svc::Dict{String,Any}) = createCoreV1NamespacedService(ctx.api, ctx.namespace, svc)
put!(ctx::KuberContext, ::Type{PersistentVolume}, pv::Dict{String,Any}) = createCoreV1PersistentVolume(ctx.api, pv)
put!(ctx::KuberContext, ::Type{PersistentVolumeClaim}, pvc::Dict{String,Any}) = createCoreV1NamespacedPersistentVolumeClaim(ctx.api, ctx.namespace, pvc)

_delopts(; kwargs...) = DeleteOptions(; preconditions=Preconditions(; kwargs...), kwargs...)
delete!(ctx::KuberContext, ::Type{Namespace}, ns::String; kwargs...) = deleteCoreV1Namespace(ctx.api, nctx.amespace, _delopts(; kwargs...))
delete!(ctx::KuberContext, ::Type{Endpoints}, epts::String; kwargs...) = deleteCoreV1NamespacedEndpoints(ctx.api, epts, ctx.namespace, _delopts(; kwargs...))
delete!(ctx::KuberContext, ::Type{Pod}, pod::String; kwargs...) = deleteCoreV1NamespacedPod(ctx.api, pod, ctx.namespace, _delopts(; kwargs...))
delete!(ctx::KuberContext, ::Type{PodTemplate}, pt::String; kwargs...) = deleteCoreV1NamespacedPodTemplate(ctx.api, pt, ctx.namespace, _delopts(; kwargs...))
delete!(ctx::KuberContext, ::Type{ReplicationController}, rc::String; kwargs...) = deleteCoreV1NamespacedReplicationController(ctx.api, rc, ctx.namespace, _delopts(; kwargs...))
delete!(ctx::KuberContext, ::Type{Service}, service::String) = deleteCoreV1NamespacedService(ctx.api, service, ctx.namespace)
delete!(ctx::KuberContext, ::Type{PersistentVolume}, pv::String; kwargs...) = deleteCoreV1PersistentVolume(ctx.api, pv, _delopts(; kwargs...))
delete!(ctx::KuberContext, ::Type{PersistentVolumeClaim}, pvc::String; kwargs...) = deleteCoreV1NamespacedPersistentVolumeClaim(ctx.api, pvc, ctx.namespace, _delopts(; kwargs...))
